import { describe, it, expect } from "vitest";
import { matchesReportSelection } from "@/lib/report-data";
const E = { propertyIds: [], categoryIds: [], recipients: [] };
const r = (p: any, rec: any, c: any) => ({ property_id: p, recipient_name: rec, category_id: c });
const R1 = r("A", "Coelba", "energia");
const R2 = r("A", "Mercado X", "alim");
const R3 = r("B", "Loja Y", "manut");
const R4 = r(null, "Roberto", "honor");
const R5 = r(null, "Restaurante Z", "alim");
const R6 = r("C", "Farmácia X", "saude");
const all = [R1,R2,R3,R4,R5,R6];
const sel = (f: any, e: any = {}) => all.filter(x => matchesReportSelection(x, {...E, ...f}, {...E, ...e}));
describe("união", () => {
  it("teste 1", () => expect(sel({propertyIds:["A","B"]}, {recipients:["Roberto"]})).toEqual([R1,R2,R3,R4]));
  it("teste 2", () => expect(sel({propertyIds:["A","B"]}, {recipients:["Roberto"],categoryIds:["saude"]})).toEqual([R1,R2,R3,R4,R6]));
  it("teste 3 sem duplicar", () => expect(sel({propertyIds:["A"]}, {recipients:["coelba "],categoryIds:["energia"]})).toEqual([R1,R2]));
  it("só categoria", () => expect(sel({categoryIds:["alim"]})).toEqual([R2,R5]));
  it("só destinatário", () => expect(sel({recipients:["Roberto","Loja Y"]})).toEqual([R3,R4]));
  it("nada selecionado", () => expect(sel({})).toEqual(all));
});
