/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppVaultRouteImport } from './routes/_authenticated/app.vault'
import { Route as AuthenticatedAppUploadRouteImport } from './routes/_authenticated/app.upload'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppPropertiesRouteImport } from './routes/_authenticated/app.properties'
import { Route as AuthenticatedAppProfilesRouteImport } from './routes/_authenticated/app.profiles'
import { Route as AuthenticatedAppImportRouteImport } from './routes/_authenticated/app.import'
import { Route as AuthenticatedAppCategoriesRouteImport } from './routes/_authenticated/app.categories'
import { Route as AuthenticatedAppCardsRouteImport } from './routes/_authenticated/app.cards'
import { Route as AuthenticatedAppBanksRouteImport } from './routes/_authenticated/app.banks'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppPropertiesIdRouteImport } from './routes/_authenticated/app.properties.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppVaultRoute = AuthenticatedAppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUploadRoute = AuthenticatedAppUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesRoute =
  AuthenticatedAppPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfilesRoute =
  AuthenticatedAppProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportRoute = AuthenticatedAppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCategoriesRoute =
  AuthenticatedAppCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCardsRoute = AuthenticatedAppCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppBanksRoute = AuthenticatedAppBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPropertiesIdRoute =
  AuthenticatedAppPropertiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppPropertiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/banks': typeof AuthenticatedAppBanksRoute
  '/app/cards': typeof AuthenticatedAppCardsRoute
  '/app/categories': typeof AuthenticatedAppCategoriesRoute
  '/app/import': typeof AuthenticatedAppImportRoute
  '/app/profiles': typeof AuthenticatedAppProfilesRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRouteWithChildren
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/upload': typeof AuthenticatedAppUploadRoute
  '/app/vault': typeof AuthenticatedAppVaultRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/properties/$id': typeof AuthenticatedAppPropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/banks': typeof AuthenticatedAppBanksRoute
  '/app/cards': typeof AuthenticatedAppCardsRoute
  '/app/categories': typeof AuthenticatedAppCategoriesRoute
  '/app/import': typeof AuthenticatedAppImportRoute
  '/app/profiles': typeof AuthenticatedAppProfilesRoute
  '/app/properties': typeof AuthenticatedAppPropertiesRouteWithChildren
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/upload': typeof AuthenticatedAppUploadRoute
  '/app/vault': typeof AuthenticatedAppVaultRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/properties/$id': typeof AuthenticatedAppPropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/banks': typeof AuthenticatedAppBanksRoute
  '/_authenticated/app/cards': typeof AuthenticatedAppCardsRoute
  '/_authenticated/app/categories': typeof AuthenticatedAppCategoriesRoute
  '/_authenticated/app/import': typeof AuthenticatedAppImportRoute
  '/_authenticated/app/profiles': typeof AuthenticatedAppProfilesRoute
  '/_authenticated/app/properties': typeof AuthenticatedAppPropertiesRouteWithChildren
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/upload': typeof AuthenticatedAppUploadRoute
  '/_authenticated/app/vault': typeof AuthenticatedAppVaultRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/properties/$id': typeof AuthenticatedAppPropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/app/audit'
    | '/app/banks'
    | '/app/cards'
    | '/app/categories'
    | '/app/import'
    | '/app/profiles'
    | '/app/properties'
    | '/app/reports'
    | '/app/upload'
    | '/app/vault'
    | '/app/'
    | '/app/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/audit'
    | '/app/banks'
    | '/app/cards'
    | '/app/categories'
    | '/app/import'
    | '/app/profiles'
    | '/app/properties'
    | '/app/reports'
    | '/app/upload'
    | '/app/vault'
    | '/app'
    | '/app/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/banks'
    | '/_authenticated/app/cards'
    | '/_authenticated/app/categories'
    | '/_authenticated/app/import'
    | '/_authenticated/app/profiles'
    | '/_authenticated/app/properties'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/upload'
    | '/_authenticated/app/vault'
    | '/_authenticated/app/'
    | '/_authenticated/app/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/vault': {
      id: '/_authenticated/app/vault'
      path: '/vault'
      fullPath: '/app/vault'
      preLoaderRoute: typeof AuthenticatedAppVaultRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/upload': {
      id: '/_authenticated/app/upload'
      path: '/upload'
      fullPath: '/app/upload'
      preLoaderRoute: typeof AuthenticatedAppUploadRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties': {
      id: '/_authenticated/app/properties'
      path: '/properties'
      fullPath: '/app/properties'
      preLoaderRoute: typeof AuthenticatedAppPropertiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profiles': {
      id: '/_authenticated/app/profiles'
      path: '/profiles'
      fullPath: '/app/profiles'
      preLoaderRoute: typeof AuthenticatedAppProfilesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/import': {
      id: '/_authenticated/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AuthenticatedAppImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/categories': {
      id: '/_authenticated/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AuthenticatedAppCategoriesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cards': {
      id: '/_authenticated/app/cards'
      path: '/cards'
      fullPath: '/app/cards'
      preLoaderRoute: typeof AuthenticatedAppCardsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/banks': {
      id: '/_authenticated/app/banks'
      path: '/banks'
      fullPath: '/app/banks'
      preLoaderRoute: typeof AuthenticatedAppBanksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/properties/$id': {
      id: '/_authenticated/app/properties/$id'
      path: '/$id'
      fullPath: '/app/properties/$id'
      preLoaderRoute: typeof AuthenticatedAppPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedAppPropertiesRoute
    }
  }
}

interface AuthenticatedAppPropertiesRouteChildren {
  AuthenticatedAppPropertiesIdRoute: typeof AuthenticatedAppPropertiesIdRoute
}

const AuthenticatedAppPropertiesRouteChildren: AuthenticatedAppPropertiesRouteChildren =
  {
    AuthenticatedAppPropertiesIdRoute: AuthenticatedAppPropertiesIdRoute,
  }

const AuthenticatedAppPropertiesRouteWithChildren =
  AuthenticatedAppPropertiesRoute._addFileChildren(
    AuthenticatedAppPropertiesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppBanksRoute: typeof AuthenticatedAppBanksRoute
  AuthenticatedAppCardsRoute: typeof AuthenticatedAppCardsRoute
  AuthenticatedAppCategoriesRoute: typeof AuthenticatedAppCategoriesRoute
  AuthenticatedAppImportRoute: typeof AuthenticatedAppImportRoute
  AuthenticatedAppProfilesRoute: typeof AuthenticatedAppProfilesRoute
  AuthenticatedAppPropertiesRoute: typeof AuthenticatedAppPropertiesRouteWithChildren
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppUploadRoute: typeof AuthenticatedAppUploadRoute
  AuthenticatedAppVaultRoute: typeof AuthenticatedAppVaultRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppBanksRoute: AuthenticatedAppBanksRoute,
  AuthenticatedAppCardsRoute: AuthenticatedAppCardsRoute,
  AuthenticatedAppCategoriesRoute: AuthenticatedAppCategoriesRoute,
  AuthenticatedAppImportRoute: AuthenticatedAppImportRoute,
  AuthenticatedAppProfilesRoute: AuthenticatedAppProfilesRoute,
  AuthenticatedAppPropertiesRoute: AuthenticatedAppPropertiesRouteWithChildren,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppUploadRoute: AuthenticatedAppUploadRoute,
  AuthenticatedAppVaultRoute: AuthenticatedAppVaultRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
